export const ACTIONS_USER = {
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_UPDATE: 'USER_UPDATE',
    USER_REGISTER: 'USER_REGISTER',
    USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
    USER_RESET_PASSWORD: 'USER_RESET_PASSWORD',
    SET_FIREBASETOKEN:'SET_FIREBASETOKEN',
    USER_UPDATE_PROFILE: 'USER_UPDATE_PROFILE',
}

export const ACTIONS_PREFERENCES = {
    PREF_SET_DRIVER : 'PREF_SET_DRIVER',
    PREF_SET_LOCALE : 'PREF_SET_LOCALE',
    PREF_SET_TIME_RANGE : 'PREF_SET_TIME_RANGE',
    PREF_SET_START_RANGE : 'PREF_SET_START_RANGE',
    PREF_SET_DEST_RANGE : 'PREF_SET_DEST_RANGE',
    PREF_LOCATION_HISTORY : 'PREF_LOCATION_HISTORY',
    PREF_LOCATION_ADD : 'PREF_LOCATION_ADD',    
    PREF_SET_PREFERENCES: 'PREF_SET_PREFERENCES',
}
export const ACTIONS_APP = {
    APP_SET_ISLOADING : 'APP_SET_ISLOADING',    
    APP_ISANDROID : 'APP_ISANDROID',
    APP_SET_AUTHORIZED : 'APP_SET_AUTHORIZED',
}

export const ACTIONS_VEHICLE = {
    VEHICLES_GET: 'VEHICLES_GET',
    VEHICLES_CLEAR: 'VEHICLES_CLEAR',    
    VEHICLES_ADD: 'VEHICLES_ADD',
    VEHICLES_DELETE: 'VEHICLES_DELETE',
    VEHICLES_SET_DEFAULT: 'VEHICLES_SET_DEFAULT',
    VEHICLES_GET_DEFAULT: 'VEHICLES_GET_DEFAULT',
}

export const ACTIONS_NEWTRIP = {
    UPDATE_STARTLOCATION: 'UPDATE_STARTLOCATION',
    UPDATE_DESTINATIONLOCATION: 'UPDATE_DESTINATIONLOCATION',
    SET_COMPLETED: 'SET_COMPLETED',
    UPDATE_ROUTEPOINTS: 'UPDATE_ROUTEPOINTS',
    CLEAR_NEWTRIP: 'CLEAR_NEWTRIP',
}

export const ACTIONS_TRIPS = {
    GET_TRIPS: 'GET_TRIPS',
    SET_TRIPS: 'SET_TRIPS',
    GET_SEARCHEDTRIPLIST: 'GET_SEARCHEDTRIPLIST',
    SET_SEARCHEDTRIPLIST: 'SET_SEARCHEDTRIPLIST',
    GET_TOP_2_SEARCHEDTRIPS: 'GET_TOP_2_SEARCHEDTRIPS',
    ADD_TRIP:'ADD_TRIP',
    UPDATE_TRIP: 'UPDATE_TRIP',
    GET_HASUPCOMINGTRIP:'GET_HASUPCOMINGTRIP',
    GET_UPCOMINGTRIP:'GET_UPCOMINGTRIP',
    SET_UPCOMINGTRIP:'SET_UPCOMINGTRIP',
    SET_HASUPCOMINGTRIP:'SET_HASUPCOMINGTRIP',
    GET_PENDINGTRIPS: 'GET_PENDINGTRIPS',
    SET_PENDINGTRIPS: 'SET_PENDINGTRIPS',
    GET_DRIVER_LOCATION:'GET_DRIVER_LOCATION',
    SET_DRIVER_LOCATION: 'SET_DRIVER_LOCATION',
    START_DRIVING: 'START_DRIVING',
    STOP_DRIVING:'STOP_DRIVING',
    DELETE_TRIP:'DELETE_TRIP',
    DEACTIVATE_TRIP:'DEACTIVATE_TRIP',
    REACTIVATE_TRIP:'REACTIVATE_TRIP',
    UPDATE_NOTE:'UPDATE_NOTE',
    UPDATE_TRIP_NOTIFICATION:'UPDATE_TRIP_NOTIFICATION',
    GET_TRIP_SEARCH_HISTORY:'GET_TRIP_SEARCH_HISTORY',
    ACCEPT_SUBSCRIPTION:'ACCEPT_SUBSCRIPTION',
    REMOVE_SUBSCRIPTION:'REMOVE_SUBSCRIPTION',
    REJECT_SUBSCRIPTION:'REJECT_SUBSCRIPTION',
    GET_REMOTE_TRIPS: 'GET_REMOTE_TRIPS'
}

export const ACTIONS_SUBSCRIBE = {
    GET_ISSUBSCRIBED : 'GET_ISSUBSCRIBED',
    SET_SUBSCRIBE : 'SET_SUBSCRIBE',
    SET_UNSUBSCRIBE : 'SET_UNSUBSCRIBE',
    SET_REQUESTSUBSCRIPTION : 'SET_REQUESTSUBSCRIPTION',
    SET_REMOTESUBSCRIPTIONS : 'GET_REMOTESUBSCRIPTIONS',
    SET_PENDINGTRIPSREQUESTS: 'SET_PENDINGTRIPSREQUESTS'
}

export const ACTION_PROFILE = {
    UPDATE_PROFILE : 'UPDATE_PROFILE',
    SUCCESS_PROFILE : 'SUCCESS_PROFILE',
    FAILED_PROFILE : 'FAILED_PROFILE',
}


export default { ACTIONS_USER, ACTIONS_VEHICLE, ACTIONS_PREFERENCES, ACTIONS_TRIPS, ACTION_PROFILE }